apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-2023-deployment # you can any name here 
  labels:
    app: project1-2023 # you can put any label as long as it is a key value pair
spec:
  replicas: 3  # define the number of cpods to deploy ( run)
  selector:
    matchLabels:
      app: project1-2023   # same as label
  template:
    metadata:
      labels:
        app: project1-2023   # same as label
    spec:
      containers:
      - name: project1-2023 # give a container any name you want
        image: devopstrainingschool/project1-2023:32
        ports:
        - containerPort: 8080  # put the container port here
